version: "3.8"
services:
  app:
    build: ./docker/dev
    ports:
      - '3400:3000'
    volumes:
      - ./:/app
    env_file:
      - .env
  db:
    image: "mysql:8"
    platform: linux/x86_64
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
      MYSQL_DATABASE: "app"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3316:3306'
  redis:
    image: "redis:7-alpine"
    ports:
      - '7002:6379'
